# Generated by Django 4.2.7 on 2025-12-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="app_users",
        ),
    ]
