-- MySQL Script generated by MySQL Workbench
-- Mon Nov  3 17:31:06 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `role` ENUM('student', 'librarian') NOT NULL,
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `ux_users_username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `ux_users_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `student_id` INT NOT NULL,
  `major` VARCHAR(100) NULL DEFAULT NULL,
  `year` INT NULL DEFAULT NULL,
  PRIMARY KEY (`student_id`),
  CONSTRAINT `fk_students_user`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`LibraryBranches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LibraryBranches` (
  `branch_id` INT NOT NULL AUTO_INCREMENT,
  `branch_name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`branch_id`),
  UNIQUE INDEX `ux_branch_name` (`branch_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`Librarians`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Librarians` (
  `librarian_id` INT NOT NULL,
  `employee_id` VARCHAR(20) NOT NULL,
  `branch_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`librarian_id`),
  UNIQUE INDEX `ux_librarians_employee` (`employee_id` ASC) VISIBLE,
  INDEX `fk_librarians_branch` (`branch_id` ASC) VISIBLE,
  CONSTRAINT `fk_librarians_user`
    FOREIGN KEY (`librarian_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_librarians_branch`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`LibraryBranches` (`branch_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`Publishers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Publishers` (
  `publisher_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(200) NULL DEFAULT NULL,
  `contact_email` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`publisher_id`),
  UNIQUE INDEX `ux_publishers_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`Authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Authors` (
  `author_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `bio` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`author_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Books` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL,
  `isbn` VARCHAR(20) NOT NULL,
  `pages` INT NULL DEFAULT NULL,
  `publication_year` YEAR NULL DEFAULT NULL,
  `publisher_id` INT NULL DEFAULT NULL,
  `branch_id` INT NULL DEFAULT NULL,
  `available_copies` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`book_id`),
  UNIQUE INDEX `ux_books_isbn` (`isbn` ASC) VISIBLE,
  INDEX `idx_books_publisher` (`publisher_id` ASC) VISIBLE,
  INDEX `idx_books_branch` (`branch_id` ASC) VISIBLE,
  CONSTRAINT `fk_books_publisher`
    FOREIGN KEY (`publisher_id`)
    REFERENCES `mydb`.`Publishers` (`publisher_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_books_branch`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`LibraryBranches` (`branch_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`BookAuthors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BookAuthors` (
  `book_id` INT NOT NULL,
  `author_id` INT NOT NULL,
  PRIMARY KEY (`book_id`, `author_id`),
  INDEX `idx_ba_author` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_ba_book`
    FOREIGN KEY (`book_id`)
    REFERENCES `mydb`.`Books` (`book_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ba_author`
    FOREIGN KEY (`author_id`)
    REFERENCES `mydb`.`Authors` (`author_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`Catalogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Catalogs` (
  `catalog_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`catalog_id`),
  UNIQUE INDEX `ux_catalogs_name` (`category_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`BookCatalogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BookCatalogs` (
  `book_id` INT NOT NULL,
  `catalog_id` INT NOT NULL,
  PRIMARY KEY (`book_id`, `catalog_id`),
  INDEX `idx_bc_catalog` (`catalog_id` ASC) VISIBLE,
  CONSTRAINT `fk_bc_book`
    FOREIGN KEY (`book_id`)
    REFERENCES `mydb`.`Books` (`book_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bc_catalog`
    FOREIGN KEY (`catalog_id`)
    REFERENCES `mydb`.`Catalogs` (`catalog_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`Loans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loans` (
  `loan_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `loan_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `due_date` DATE NOT NULL,
  `return_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`loan_id`),
  INDEX `idx_loans_user` (`user_id` ASC) VISIBLE,
  INDEX `idx_loans_book` (`book_id` ASC) VISIBLE,
  CONSTRAINT `fk_loans_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_loans_book`
    FOREIGN KEY (`book_id`)
    REFERENCES `mydb`.`Books` (`book_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`Reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservations` (
  `reservation_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `reservation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('active', 'fulfilled', 'cancelled') NOT NULL DEFAULT 'active',
  PRIMARY KEY (`reservation_id`),
  INDEX `idx_res_user` (`user_id` ASC) VISIBLE,
  INDEX `idx_res_book` (`book_id` ASC) VISIBLE,
  CONSTRAINT `fk_res_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_res_book`
    FOREIGN KEY (`book_id`)
    REFERENCES `mydb`.`Books` (`book_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`Fines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fines` (
  `fine_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `loan_id` INT NOT NULL,
  `amount` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
  `paid` TINYINT(1) NOT NULL DEFAULT 0,
  `date_issued` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`fine_id`),
  INDEX `idx_fines_loan` (`loan_id` ASC) VISIBLE,
  INDEX `idx_fines_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_fines_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_fines_loan`
    FOREIGN KEY (`loan_id`)
    REFERENCES `mydb`.`Loans` (`loan_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`Notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Notifications` (
  `notification_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `message` TEXT NOT NULL,
  `notification_type` ENUM('overdue', 'reservation', 'general') NOT NULL DEFAULT 'general',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_read` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`notification_id`),
  INDEX `idx_notifications_user` (`user_id` ASC),
  CONSTRAINT `fk_notifications_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Additional database objects: Views, Triggers, Procedures, Cursors
-- -----------------------------------------------------

-- -----------------------------------------------------
-- View `mydb`.`v_overdue_loans`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`v_overdue_loans`;
CREATE VIEW `mydb`.`v_overdue_loans` AS
SELECT l.loan_id, u.username, b.title, l.due_date FROM Loans l
JOIN Users u ON l.user_id = u.user_id JOIN Books b ON l.book_id = b.book_id
WHERE l.return_date IS NULL AND l.due_date < CURDATE();

-- -----------------------------------------------------
-- Trigger `mydb`.`trg_overdue_notification`
-- -----------------------------------------------------
DROP TRIGGER IF EXISTS `mydb`.`trg_overdue_notification`;
DELIMITER $$
CREATE TRIGGER `mydb`.`trg_overdue_notification`
AFTER UPDATE ON Loans
FOR EACH ROW
BEGIN
	IF NEW.return_date IS NULL AND NEW.due_date < CURDATE() THEN
		INSERT INTO Notifications(user_id, message, notification_type)
        VALUES (NEW.user_id, CONCAT('Loan ', NEW.loan_id, ' is overdue!'), 'overdue');
    END IF;
END$$
DELIMITER ;

-- -----------------------------------------------------
-- Procedure `mydb`.`sp_user_loans`
-- -----------------------------------------------------
DROP PROCEDURE IF EXISTS `mydb`.`sp_user_loans`;
DELIMITER $$
CREATE PROCEDURE `mydb`.`sp_user_loans` (IN uid INT)
BEGIN
    SELECT b.title, l.loan_date, l.due_date, l.return_date
    FROM Loans l
    JOIN Books b ON l.book_id = b.book_id
    WHERE l.user_id = uid;
END$$
DELIMITER ;

-- -----------------------------------------------------
-- Procedure `mydb`.`sp_process_overdue` (with cursor example)
-- -----------------------------------------------------
DROP PROCEDURE IF EXISTS `mydb`.`sp_process_overdue`;
DELIMITER $$
CREATE PROCEDURE `mydb`.`sp_process_overdue` ()
BEGIN
    DECLARE done INT DEFAULT FALSE;
    DECLARE loanId INT;
    DECLARE cur CURSOR FOR
        SELECT loan_id FROM Loans WHERE return_date IS NULL AND due_date < CURDATE();
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

    OPEN cur;
    read_loop: LOOP
        FETCH cur INTO loanId;
        IF done THEN
            LEAVE read_loop;
        END IF;
        INSERT INTO Fines(user_id, loan_id, amount)
        SELECT user_id, loan_id, 5.00 FROM Loans WHERE loan_id = loanId;
    END LOOP;
    CLOSE cur;
END$$
DELIMITER ;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
