# Generated by Django 5.2.8 on 2025-11-20 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'authors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Catalogs',
            fields=[
                ('catalog_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalogs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=9)),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Librarybranches',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'librarybranches',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('publisher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'publishers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.users')),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('publication_year', models.TextField(blank=True, null=True)),
                ('available_copies', models.IntegerField()),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.librarybranches')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.publishers')),
            ],
            options={
                'db_table': 'books',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_date', models.DateTimeField()),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.users')),
            ],
            options={
                'db_table': 'loans',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('fine_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('paid', models.IntegerField()),
                ('date_issued', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.users')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.loans')),
            ],
            options={
                'db_table': 'fines',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField()),
                ('is_read', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.users')),
            ],
            options={
                'db_table': 'notifications',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateTimeField()),
                ('status', models.CharField(max_length=9)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.users')),
            ],
            options={
                'db_table': 'reservations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Librarians',
            fields=[
                ('librarian', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.users')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.librarybranches')),
            ],
            options={
                'db_table': 'librarians',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bookauthors',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.books')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.authors')),
            ],
            options={
                'db_table': 'bookauthors',
                'managed': True,
                'unique_together': {('book', 'author')},
            },
        ),
        migrations.CreateModel(
            name='Bookcatalogs',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.books')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.catalogs')),
            ],
            options={
                'db_table': 'bookcatalogs',
                'managed': True,
                'unique_together': {('book', 'catalog')},
            },
        ),
    ]
