# Generated by Django 5.2.8 on 2025-11-20 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bookauthors',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bookcatalogs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={},
        ),
        migrations.AlterModelOptions(
            name='catalogs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fines',
            options={},
        ),
        migrations.AlterModelOptions(
            name='librarians',
            options={},
        ),
        migrations.AlterModelOptions(
            name='librarybranches',
            options={},
        ),
        migrations.AlterModelOptions(
            name='loans',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={},
        ),
        migrations.AlterModelOptions(
            name='publishers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reservations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.AddField(
            model_name='bookauthors',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='bookcatalogs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookauthors',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.authors'),
        ),
        migrations.AlterField(
            model_name='bookauthors',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.books'),
        ),
        migrations.AlterField(
            model_name='bookcatalogs',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.books'),
        ),
        migrations.AlterField(
            model_name='bookcatalogs',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.catalogs'),
        ),
        migrations.AlterField(
            model_name='books',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.librarybranches'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publication_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.publishers'),
        ),
        migrations.AlterField(
            model_name='fines',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.loans'),
        ),
        migrations.AlterField(
            model_name='fines',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users'),
        ),
        migrations.AlterField(
            model_name='librarians',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.librarybranches'),
        ),
        migrations.AlterField(
            model_name='librarians',
            name='librarian',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.users'),
        ),
        migrations.AlterField(
            model_name='loans',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.books'),
        ),
        migrations.AlterField(
            model_name='loans',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.books'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.users'),
        ),
    ]
