# Generated by Django 5.1.7 on 2025-12-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_db_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
